// <auto-generated />
namespace PTCG_Tracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addmigrationFirstMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmigrationFirstMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202012041901194_add-migration FirstMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
